module.exports = {
  positions: [
    {
      slug: "senior-process-engineer",
      role: "Process Engineer",
      location: "Sion, Switzerland",
      level: "Senior Level",
      brief:
        "As a Process Engineer, you will be responsible for the Process design and development and optimisation of chemical recycling systems from inception through to start up, designing, running, testing and upscaling systems and processes, and upscaling the newly developed DePoly pilot plant.",
      dept: "Technology",
      hours: "Full-time",
      location: "Sion, Switzerland",
      responsibilities: [
        "Process design and development and optimisation of chemical recycling systems from inception through to start up.",
        "Designing, upgrading and troubleshooting systems and processes. ",
        "Upscaling the newly developed DePoly recycling plant.",
        "Utilise process simulation software to test and find the most appropriate production strategies. ",
        "Develop standardized operating instructions for processes to ensure product quality",
      ],
      skills: [
        "Bachelor or Master degree in chemical engineering, process engineering or related disciplines ",
        "Work experience in an industrial environment, or a solid foundation in the technology sector ",
        "Expert in process design and optimization, equipment sizing and upscaling studies",
        "Expert in process simulation in accordance with industrial standards ",
        "Assess processes, take measurements and interpret data ",
        "Comfortable working in a fast-paced industrial environment ",
        "Be fluent in English, and have an intermediate knowledge of French. ",
        "Have a Swiss working permit or be eligible to work in Switzerland",
      ],
      offer: [
        "A stimulating working environment.",
        "The chance to grow with our company and make a real change.",
        "Become involved in the scaling up of new recycling technologies.",
      ],
    },
    {
      slug: "senior-chemical-engineer",
      role: "Chemical Engineer",
      location: "Sion, Switzerland",
      level: "Senior Level",
      brief:
        "As a Chemical Engineer you will be responsible for process design, development and optimisation of chemical recycling systems. You will design, run, test and upgrade systems and processes. You will develop and standardise operating instructions to ensure product quality, internal auditing, and environmental and quality management of current and future processes to assess feasibility.",
      dept: "Technology",
      hours: "Full-time",
      location: "Sion, Switzerland",
      responsibilities: [
        "Process design, development and optimisation of chemical recycling systems from inception through to start up.",
        "Designing, running, testing and upgrading systems and processes",
        "Upgrading the newly developed DePoly recycling demonstrator plant and eventual commercial plant",
        "Utilise process simulation software to test and find the most appropriate production strategies.",
        "Develop standardized operating instructions for processes to ensure product quality",
        "Internal auditing, and both environmental and quality management of current and future processes to assess feasibility.",
      ],
      skills: [
        "Bachelor/Master degree in chemical engineering, polymer engineering or related disciplines from high ranked/prestigious university, knowledge on waste and waste water management, renewable energy, HSE management and process optimization is highly desirable.",
        "International experience (internships accepted)",
        "Design, prototyping and validation of the filtration technology",
        "A solid foundation in quality management and international standards",
        "Experience working with/in environmental, quality and food management standards such as ISO 14001, ISO 9001, ISO 22000 ",
        "Experience with process modelling software such as Comsol, Aspen HYSYS/ Aspen PLUS, MATLAB",
        "Experience in depolymerization chemistry, scale up, and process optimization.",
        "Experience in water treatment",
        "Work experience in an industrial environment, or a solid foundation in the technology sector",
        "Fluent in Arabic (C1-C2 accepted) with basic knowledge in English and French.",
        "Have a Swiss working permit or be eligible to work in Switzerland",
      ],
      offer: [
        "A stimulating working environment.",
        "The chance to grow with our company and make a real change.",
        "Become involved in the scaling up of new recycling technologies.",
      ],
    },
  ],
};
